---
title: "Presentaciones y conferencias"
---
-  Informe de Estabilidad Financiera Regional 2020. IX CMCA-CCSBSO, modalidad virtual (Feb. 12, 2020)

-  Informe de Estabilidad Financiera Regional 2019. VIII CMCA-CCSBSO, Punta Cana, República Dominicana (Feb. 15, 2020)


-  Avances en la aplicación de los estándares para el desarrollo del mercado de deuda soberana regional. Asamblea de directores, BCIE, Tegucigalpa, Honduras (Oct. 31, 2018)

- Propuesta de Plan de Trabajo del Grupo de Estabilidad Financiera Regional. VII CMCA-CCSBSO, Tegucigalpa, Honduras (Jul. 27, 2018)

- Macroprudential policy implementation and relationship with other policies. X BIS-CEMLA Roundtable: Macroprudential frameworks, implementation and relationship with other policies, Lima, Perú (May. 15-16, 2017)

- Referentes predictivos para el pronóstico de la inflación interanual en los países de Centroamérica y República Dominicana. X Foro de Investigadores de Banco Centrales del CMCA, San José, Costa Rica (Jul. 14-15, 2016)
