---
title: "Publicaciones"
---
-  <strong>Ortiz, L.</strong> (2020). Propuesta De Un Indicador De Riesgo Sistémico Para El Triángulo Norte De Centroamérica. Documento de Trabajo No. 3, septiembre 2020. Secretaría Ejecutiva del Consejo Monetario Centroamericano. <a href="http://www.secmca.org/wp-content/uploads/2020/09/PROPUESTA-DE-UN-INDICADOR-DE-RIESGO-SIST%C3%89MICO-PARA-EL-TRI%C3%81NGULO-NORTE-DE-CENTROAM%C3%89RICA.pdf" class="email">[PDF]</a> 


-  <strong>Ortiz, L.</strong> (2019). El Mapa de Calor. Instrumento para la identificación de vulnerabilidad macroeocnómicas para la región. Notas Económicas Regionales No. 102, abril 2019. Secretaría Ejecutiva del Consejo Monetario Centroamericano. <a href="http://www.secmca.org/wp-content/uploads/2019/05/Nota-Económica-Regional-No.-102.pdf" class="email">[PDF]</a> 

- <strong>Ortiz, L.</strong> (2018). Requerimiento de Capital Contracíclico y Gap de Crédito en Centroamérica. Notas Económicas Regionales No. 97, agosto 2018. Secretaría Ejecutiva del Consejo Monetario Centroamericano.<a href="http://www.secmca.org/wp-content/uploads/2019/02/articulo97AGO2018.pdf" class="email">[PDF]</a>  

-  <strong>Ortiz, L.</strong> y Pascual, O. (2016). Referentes predictivos para el pronóstico de la inflación interanual en los países de Centroamérica y República Dominicana. Documento de Trabajo No. 1, 2016. Secretaría Ejecutiva del Consejo Monetario Centroamericano. <a href="http://www.secmca.org/wp-content/uploads/2019/02/1.-01_2016-pron%C3%B3stico-de-la-inflaci%C3%B3n-interanual.pdf" class="email">[PDF]</a>  

- <strong>Ortiz, L.</strong> (2015). Hacia la aplicación de test de estrés al crédito a los principales bancos de Centroamérica. Documento de Trabajo No. 2, 2015. Secretaría Ejecutiva del Consejo Monetario Centroamericano. <a href="http://www.secmca.org/wp-content/uploads/2019/02/2.-02_2015-aplicaci%C3%B3n-de-test-de-estr%C3%A9s-al-cr%C3%A9dito.pdf" class="email">[PDF]</a>   

- <strong>Ortiz, L.</strong> (2014). Estimación de Curvas de Rendimiento aplicación del modelo Nelson-Siegel para El Salvador. Documentos Ocasionales No. 3, 2014. Banco Central de Reserva de El Salvador. <a href="http://www.bcr.gob.sv/bcrsite/uploaded/content/category/2056392058.pdf" class="email">[PDF]</a>  

- <strong>Ortiz, L.</strong> (2008). Impuestos y Subvenciones en El Salvador en el Marco del Sistema de Cuentas Nacionales 1993. Boletín Económico 2008. Banco Central de Reserva de El Salador. <a href="http://www.bcr.gob.sv/bcrsite/uploaded/content/category/1532378855.pdf" class="email">[PDF]</a>  
